chore: bump vitest (#1001)
# Motivation

We want the latest improvements in vitest.

# Notes

It seems we used to inherits the Node types through that dependency as
bumping without further changes leads to following build error (for
example):

> src/utils/debounce.utils.ts:14:14 - error TS2503: Cannot find
namespace 'NodeJS'.
>
> 14   let timer: NodeJS.Timer | undefined;

or

> src/account_identifier.ts:14:35 - error TS2580: Cannot find name
'Buffer'. Do you need to install type definitions for node? > Try `npm i
--save-dev @types/node`.
>
> 14     const bytes = Uint8Array.from(Buffer.from(hex, "hex"));

That's why this pr also adds `@types/node`.

# Changes

- `npm rm vitest && npm i vitest`
- `npm i @types/node`

---------

Signed-off-by: David Dal Busco <david.dalbusco@dfinity.org>