fix: missing did mock fields (#1037)
# Motivation

There are new did fields that were merged in #1033 that were not
implemented in the mock for the tests (because the PR passed). As a
result, tests do not run currently on main.

```
packages/ic-management/src/ic-management.canister.spec.ts:400:13 - error TS2739: Type '{ status: { running: null; }; memory_size: bigint; cycles: bigint; settings: { freezing_threshold: bigint; controllers: Principal[]; memory_allocation: bigint; compute_allocation: bigint; reserved_cycles_limit: bigint; log_visibility: { ...; }; wasm_memory_limit: bigint; wasm_memory_threshold: bigint; }; ... 4 more ...' is missing the following properties from type 'canister_status_result': ready_for_migration, version

400       const response: CanisterStatusResponse = {
                ~~~~~~~~

packages/sns/src/mocks/governance.mock.ts:38:14 - error TS2741: Property 'extension_operations' is missing in type '{ custom_functions: []; description: [string]; is_critical: [false]; name: [string]; native_functions: []; topic: [{ ApplicationBusinessLogic: null; }]; }' but required in type 'TopicInfo'.

38 export const topicInfoMock: TopicInfo = {
```

# Changes

- Add missing fields to mock

Signed-off-by: David Dal Busco <david.dalbusco@dfinity.org>