build(core): set module resolution to bundler (#1103)
# Motivation

Migrating to the `@icp-sdk` (#1044) requires importing modules (agent,
identity etc.) from sub-entries - e.g. `@icp-sdk/core/agent` instead of
`@dfinity/agent`.

Our current `moduleResolution: node` set in `tsconfig.json` cannot
resolve those kind of path. Without any changes, it leads to issue at
build time like:

> src/utils/governance.utils.ts:7:32 - error TS2307: Cannot find module
'@icp-sdk/core/principal' or its corresponding type declarations.
> There are types at
'/Users/daviddalbusco/projects/dfinity/ic-js/node_modules/@icp-sdk/core/lib/esm/principal/index.d.ts',
but this result could not be resolved under your current
'moduleResolution' setting. Consider updating to 'node16', 'nodenext',
or 'bundler'.

That is why we are switching to a more modern [module
resolution](https://www.typescriptlang.org/tsconfig/#moduleResolution)
approach, `bundler`.

# Notes

We switch to `bundler` because we are generating JS with a tool -
esbuild - and not TSC itself.

# Changes

- Set `moduleResolution: bundler`.

Signed-off-by: David Dal Busco <david.dalbusco@dfinity.org>