feat: spawning_neurons_count nns metrics (#982)
# Motivation

I merged the weekly Candid PR #980 and noticed a new field related to
the recent NNS `get_metrics` PR #977. This mapping includes the
additional field `spawning_neurons_count`.

# Notes

For some reasons tests passed in CI in #980 but, actually, when I run
the test on `main` now they don't as this field is missing. i.e. we need
this PR.

> packages/nns/src/governance.canister.spec.ts:2410:11 - error TS2741:
Property 'spawning_neurons_count' is missing in type '{
total_maturity_e8s_equivalent: bigint;
not_dissolving_neurons_e8s_buckets: [bigint, number][];
dissolving_neurons_staked_maturity_e8s_equivalent_sum: bigint;
garbage_collectable_neurons_count: bigint; ... 36 more ...;
seed_neuron_count: bigint; }' but required in type
'GovernanceCachedMetrics'.
>
>2410     const rawMetrics: RawGovernanceCachedMetrics = {
>               ~~~~~~~~~~
>
>  packages/nns/candid/governance.d.ts:281:3
>    281   spawning_neurons_count: bigint;
>          ~~~~~~~~~~~~~~~~~~~~~~
>    'spawning_neurons_count' is declared here.

# Changes

- Map field for response and test

Signed-off-by: David Dal Busco <david.dalbusco@dfinity.org>