Upgrade IC candids (#943)
# Motivation

To get the latest changes in the disburse maturity API (specifically,
the new argument `account_identifier_to_disburse_to`), this PR upgrades
the Candid files.

---

**Drive-by fix:**

The `get_metrics` function was implemented as a `composite_query` (it
shouldn't matter how the request is made from the front-end side), but
the `compile-idl-js` script is not expecting this and fails.

```
scripts/compile-idl-js
error: parser error
    ┌─ /var/folders/jq/281t2r192m32y1m9kk81356w0000gn/T/tmp.bGm6fkMD6h:935:61
    │
935 │   get_metrics : (GetMetricsRequest) -> (GetMetricsResponse) composite_;
    │                                                             ^^^^^^^^^^ Unexpected token
    │
    = Expects one of ";", "composite_query", "oneway", "query", "}"

Error: Candid parser error: Unrecognized token `Id("composite_")` found at 22820:22830
Expected one of ";", "composite_query", "oneway", "query" or "}"

Caused by:
    Unrecognized token `Id("composite_")` found at 22820:22830
    Expected one of ";", "composite_query", "oneway", "query" or "}"
```

# Changes

- Update `scripts/compile-idl-js` ([the
commit](https://github.com/dfinity/ic-js/pull/943/commits/82fa373113da9c71572d9f7379812861e0086c46))
to treat composite_query the same as a regular query.
- Run `./scripts/import-candid` to upgrade Candid files to the latest
IC.
- Run `scripts/compile-idl-js`.

# Tests

- Updated to test `account_identifier_to_disburse_to` field support.
# Todos

- [ ] Add entry to changelog (if necessary).

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>