test(canisters): fix "is not a module" (#1215)
# Motivation

Fix `npm run test`:

```
❯ npm run test packages/canisters/src/index.spec.ts

packages/canisters/src/index.spec.ts:3:25 - error TS2306: File '/Users/daviddalbusco/projects/dfinity/ic-js/packages/canisters/index.d.ts' is not a module.

3     await expect(import("@icp-sdk/canisters")).rejects.toThrow(
                          ~~~~~~~~~~~~~~~~~~~~


Found 1 error in packages/canisters/src/index.spec.ts:3




```