test(nns): fix missing new did field id in mocks (#1216)
# Motivation

After updating Candid files in #1209 tests are now failing locally at
least.

e.g.

```
packages/nns/src/canisters/governance/response.converters.spec.ts:95:10 - error TS2353: Object literal may only specify known properties, and 'id' does not exist in type '[] | [NeuronId]'.

95     id: {id: 987n},
            ~~

  packages/nns/src/candid/governance.d.ts:771:3
    771   id: [] | [NeuronId];
          ~~
    The expected type comes from property 'id' which is declared here on type 'NeuronInfo'
```

# Changes

- Add missing ID to mocks

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>